import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowUp, ArrowUpRight, BookOpen, Check, ChevronRight, CircleAlert, FileCode2, GitFork, Loader2, MessageSquare, Plus, Sparkles, X } from 'lucide-react';
import { post, enc } from './api';
import type { ChatResponse, Citation, CodeNode } from './types';

type Turn = {id: number; question: string; answer?: ChatResponse; error?: string};
function RichText({text}: {text: string}) {
  // Deliberately render plain React text; repository content cannot inject HTML or remote images.
  return <>{text.split(/(`[^`\n]+`|\*\*[^*\n]+\*\*)/g).map((part, index) => part.startsWith('`') ? <code key={index}>{part.slice(1,-1)}</code> : part.startsWith('**') ? <strong key={index}>{part.slice(2,-2)}</strong> : <span key={index}>{part}</span>)}</>;
}
export default function Assistant({analysisId, selected, ragReady, aiStatus, onCitation, onHighlights, onClearSelection, request}: {
  analysisId: string; selected: CodeNode | null; ragReady: boolean; aiStatus: string; onCitation: (citation: Citation) => void; onHighlights: (ids: string[]) => void; onClearSelection: () => void;
  request: {seq: number; action: 'explain'|'dependencies'|'dependents'; node: CodeNode} | null;
}) {
  const [input, setInput] = useState(''); const [turns, setTurns] = useState<Turn[]>([]); const [busy, setBusy] = useState(false);
  const scroll = useRef<HTMLDivElement>(null); const seen = useRef(0); const inputRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => {scroll.current?.scrollTo({top: scroll.current.scrollHeight, behavior: 'smooth'});}, [turns, busy]);
  const send = async (question: string, action?: 'explain'|'dependencies'|'dependents', node = selected) => {
    if (!question.trim() || busy || (!ragReady && action !== 'dependencies' && action !== 'dependents')) return;
    const id = Date.now();
    const history = turns.slice(-4).flatMap(turn => [{role: 'user', content: turn.question.slice(0,4000)}, ...(turn.answer ? [{role: 'assistant', content: turn.answer.blocks.map(block => block.text).join('\n').slice(0,4000)}] : [])]);
    setTurns(current => [...current, {id, question}]); setInput(''); setBusy(true);
    try {
      const answer = await post<ChatResponse>(`/analyses/${enc(analysisId)}/chat`, {message: question, selectedNodeId: node?.id, history, ...(action ? {action} : {})});
      setTurns(current => current.map(turn => turn.id === id ? {...turn, answer} : turn)); onHighlights(answer.relatedNodeIds);
    } catch (error) {setTurns(current => current.map(turn => turn.id === id ? {...turn, error: error instanceof Error ? error.message : 'Unable to answer this question.'} : turn));}
    finally {setBusy(false);}
  };
  useEffect(() => {if (request && request.seq !== seen.current && !busy) {seen.current = request.seq; void send(request.action === 'explain' ? `Explain ${request.node.name}.` : request.action === 'dependencies' ? `What does ${request.node.name} depend on?` : `What depends on ${request.node.name}?`, request.action, request.node);}}, [request, busy]);
  const submit = (event: FormEvent) => {event.preventDefault(); void send(input);};
  const suggestions = selected ? ['Explain this file', 'What depends on this?', 'What does this depend on?'] : ['How is this project structured?', 'How does authentication work?', 'Where are the API routes?'];
  return <aside className="assistant-panel" aria-label="Codebase assistant"><div className="panel-heading"><span className="assistant-mark"><Sparkles size={14}/></span><h2>Ask your codebase</h2><button className="icon-button" title="New conversation" aria-label="New conversation" disabled={busy || !turns.length} onClick={() => {setTurns([]); onHighlights([]);}}><Plus size={17}/></button></div>
    <div className="assistant-scroll" ref={scroll} aria-live="polite">
      {turns.length === 0 ? <div className="assistant-welcome"><div className="welcome-icon"><Sparkles size={22}/></div><h3>The context you need.<br/>Right where you need it.</h3><p>Explore how things connect. Every answer is grounded in your repository, with sources you can open.</p><div className="suggestion-label">A GOOD PLACE TO START</div><div className="suggestions">{suggestions.map((suggestion, index) => <button key={suggestion} disabled={!ragReady && (!selected || index === 0)} title={!ragReady && (!selected || index === 0) ? aiStatus : undefined} onClick={() => void send(suggestion, selected ? (['explain','dependents','dependencies'] as const)[index] : undefined)}><span>{suggestion}</span><ChevronRight size={14}/></button>)}</div><div className="assistant-tip"><GitFork size={15}/><span>Select a node on the map to give your question a little more context.</span></div></div> : turns.map(turn => <div className="chat-turn" key={turn.id}><div className="question-heading"><span className="avatar">Y</span><span>You</span></div><p className="question-text">{turn.question}</p><div className="answer-heading"><Sparkles size={14}/><span>Atlas</span>{turn.answer && <span className="answer-mode">{turn.answer.mode === 'graph' ? 'Static analysis' : 'Repository evidence'}</span>}</div>{turn.error ? <div className="answer-error"><CircleAlert size={15}/><p>{turn.error}</p></div> : turn.answer ? <div className="answer-content">{turn.answer.blocks.map((block, index) => <div className={`answer-block ${block.kind}`} key={index}>{block.kind !== 'fact' && <span className="claim-label">{block.kind === 'inference' ? 'Inference' : 'Not established'}</span>}<p><RichText text={block.text}/></p>{block.citationIds.length > 0 && <div className="citations">{block.citationIds.map(id => {const citation = turn.answer!.citations.find(item => item.id === id); return citation ? <button key={id} title={`${citation.path}:${citation.startLine}-${citation.endLine}`} onClick={() => onCitation(citation)}><FileCode2 size={11}/><span>{citation.path.split('/').pop()}</span><span className="citation-line">:{citation.startLine}{citation.endLine !== citation.startLine ? `–${citation.endLine}` : ''}</span><ArrowUpRight size={10}/></button> : null;})}</div>}</div>)}{turn.answer.warnings.length > 0 && <div className="answer-warnings">{turn.answer.warnings.map((warning,index) => <p key={index}>{warning}</p>)}</div>}<div className="answer-proof"><Check size={11}/>{turn.answer.citations.length} source{turn.answer.citations.length !== 1 ? 's' : ''} · {turn.answer.mode === 'graph' ? 'Resolved relationships' : 'Citations validated'}</div></div> : <div className="answer-loading"><span className="thinking-dots"><i/><i/><i/></span><span>Gathering repository evidence</span></div>}</div>)}
    </div>
    <div className="assistant-bottom">{!ragReady && <div className="ai-status"><BookOpen size={13}/><span>{aiStatus}</span></div>}{selected && <div className="selection-context"><FileCode2 size={12}/><span>{selected.name}</span><button title="Clear question context" aria-label="Clear question context" onClick={onClearSelection}><X size={12}/></button></div>}<form className="composer" onSubmit={submit}><textarea ref={inputRef} value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => {if (event.key === 'Enter' && !event.shiftKey) {event.preventDefault(); void send(input);}}} placeholder={selected ? `Ask about ${selected.name}…` : 'Ask anything about this repository…'} rows={3} aria-label="Ask about this repository" maxLength={4000}/><div className="composer-footer"><span><MessageSquare size={11}/> {selected ? 'Selection context' : 'Repository context'}</span><button type="submit" className="send-button" disabled={busy || !ragReady || !input.trim()} title={!ragReady ? aiStatus : 'Send question'} aria-label="Send question">{busy ? <Loader2 size={15} className="spin"/> : <ArrowUp size={16}/>}</button></div></form><p className="composer-note">Sources first. Assumptions made explicit.</p></div>
  </aside>;
}
