// Generated by scripts/generate_contracts.py. Edit backend/navigator/responses.py.
export interface Analysis {
  id: string;
  repositoryId: string;
  repositoryName: string;
  commitSha: string;
  status: "queued" | "running" | "ready" | "failed" | "cancelled";
  phase: string;
  graphReady: boolean;
  ragReady: boolean;
  jobId: string;
  counts: Counts;
  languages: Array<string>;
  createdAt: string;
  warnings: Array<string>;
  overview?: Overview;
  error?: string;
}
export interface AnswerBlock {
  text: string;
  kind: "fact" | "inference" | "unknown";
  citationIds: Array<string>;
}
export interface Capabilities {
  languages: Array<LanguageCapability>;
  services: Services;
  mode: "local" | "production";
}
export interface ChatResponse {
  blocks: Array<AnswerBlock>;
  citations: Array<Citation>;
  relatedNodeIds: Array<string>;
  mode: "rag" | "graph";
  warnings: Array<string>;
}
export interface Citation {
  id: string;
  analysisId: string;
  fileId: string;
  path: string;
  commitSha: string;
  startLine: number;
  endLine: number;
  chunkId?: string;
  label?: string;
}
export interface CodeEdge {
  id: string;
  source: string;
  target: string;
  kind: "contains" | "imports" | "reexports" | "references" | "calls";
  fileId?: string;
  startLine?: number;
  endLine?: number;
  specifier?: string;
  resolution: "structural" | "resolved";
  typeOnly?: boolean;
  dynamic?: boolean;
  count?: number;
  edgeIds?: Array<string>;
}
export interface CodeNode {
  id: string;
  kind: "repository" | "module" | "file" | "symbol" | "external";
  name: string;
  path?: string;
  fileId?: string;
  parentId?: string;
  language?: string;
  symbolKind?: string;
  startLine?: number;
  endLine?: number;
  startByte?: number;
  endByte?: number;
  signature?: string;
  exported?: boolean;
  tags?: Array<string>;
}
export interface Counts {
  files: number;
  symbols: number;
  edges: number;
  chunks: number;
}
export interface GraphData {
  nodes: Array<CodeNode>;
  edges: Array<CodeEdge>;
  omittedNodes: number;
  omittedEdges: number;
}
export interface Job {
  id: string;
  analysisId: string;
  status: "queued" | "running" | "ready" | "failed" | "cancelled";
  phase: string;
  completed: number;
  total: number;
  message?: string;
  error?: string;
  cancelRequested?: boolean;
  nextAttemptAt?: string;
}
export interface LanguageCapability {
  id: string;
  label: string;
  status: "supported" | "planned";
  capabilities: Array<string>;
}
export interface Overview {
  frameworks: Array<string>;
  entryPoints: Array<string>;
  routes: Array<Record<string, unknown>>;
  integrations: Array<string>;
  summary?: string;
  citations?: Array<Citation>;
  blocks?: Array<AnswerBlock>;
}
export interface Repository {
  id: string;
  owner: string;
  name: string;
  url: string;
  defaultBranch: string;
  latestAnalysisId?: string;
  createdAt: string;
}
export interface RepositoryList {
  repositories: Array<Repository>;
  analyses: Array<Analysis>;
}
export interface SearchResponse {
  results: Array<SearchResult>;
  total: number;
}
export interface SearchResult {
  id: string;
  kind: string;
  name: string;
  path: string;
  startLine?: number;
  symbolKind?: string;
}
export interface Services {
  database: boolean;
  gemini: boolean;
  queue: boolean;
}
export interface SourceFile {
  id: string;
  analysisId: string;
  path: string;
  language: string;
  content: string;
  lineCount: number;
  redacted?: boolean;
}
export interface Submission {
  repository: Repository;
  analysis: Analysis;
  job: Job;
}
export interface TreeEntry {
  id: string;
  path: string;
  name: string;
  kind: "file" | "directory";
  language?: string;
  childCount?: number;
}
export interface TreeResponse {
  entries: Array<TreeEntry>;
}
export type GraphLevel = 'modules' | 'files' | 'symbols';
export type Direction = 'both' | 'dependencies' | 'dependents';
