"""Export FastAPI OpenAPI and TypeScript types from the public Pydantic models."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from navigator.api.main import create_app
from navigator.config import Settings
from navigator import responses

MODELS = (responses.RepositoryList, responses.Submission, responses.GraphData,
          responses.SourceFile, responses.TreeResponse, responses.SearchResponse,
          responses.ChatResponse, responses.Capabilities)


def ts_type(schema):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(value) for value in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema['items'])}>"
    if kind == "object":
        return "Record<string, unknown>"
    return {"string": "string", "integer": "number", "number": "number",
            "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def main():
    definitions = {}
    for model in MODELS:
        schema = model.model_json_schema()
        definitions.update(schema.pop("$defs", {}))
        definitions[model.__name__] = schema
    output = ["// Generated by scripts/generate_contracts.py. Edit backend/navigator/responses.py."]
    for name, schema in sorted(definitions.items()):
        required = schema.get("required", [])
        output.append(f"export interface {name} {{")
        for prop, value in schema.get("properties", {}).items():
            optional = "" if prop in required else "?"
            # HTTP responses omit None; optional fields need no explicit null.
            value_type = ts_type(value)
            if prop not in required:
                value_type = value_type.replace(" | null", "")
            output.append(f"  {prop}{optional}: {value_type};")
        output.append("}")
    output += ["export type GraphLevel = 'modules' | 'files' | 'symbols';",
               "export type Direction = 'both' | 'dependencies' | 'dependents';", ""]
    (ROOT / "apps/web/src/types.ts").write_text("\n".join(output), encoding="utf-8")
    app = create_app(Settings(_env_file=None, NAVIGATOR_MODE="local"))
    directory = ROOT / "contracts"
    directory.mkdir(exist_ok=True)
    (directory / "openapi.json").write_text(json.dumps(app.openapi(), indent=2) + "\n", encoding="utf-8")
    print("Generated public API contracts and frontend types.")


if __name__ == "__main__":
    main()
